meta_product_name: "Lev&Traz"
meta_title: "Lev&Traz | Faster & cheaper deliveries and an easy way to make money on your trip"
meta_description: "Lev&Traz is a community delivery solution that connects people who need to send something with someone going that way, anyway. By working together as a community we can make shipping easier, sustainable, cost-effective and friendly. Lev&Traz is the community that delivers."
meta_image: "https://res.cloudinary.com/danielujikawa/image/upload/v1544801518/Backgrounds/og_image.jpg"                       # should exist in `app/assets/images/`
